config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :classrooms, only: [:index, :create, :destroy], defaults: {format: :json}
  root "classrooms#index"

  resources :courses
  resources :students
  devise_scope :user do
    post 'login' => 'sessions#create', :as => 'login'
    post 'logout' => 'sessions#destroy', :as => 'logout'
    get 'current_user' => 'sessions#show_current_user', :as => 'current_user'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolAndClass</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar">
      <div class="container-fluid expanded-panel">
        <div class="row">
          <div id="logo" class="col-xs-12 col-sm-2">
            <a href="/">DevOOPS</a>
          </div>
          <div id="top-panel" class="col-xs-12 col-sm-10">
            <div class="row">
              <div class="col-xs-8 col-sm-4">
                <a href="#" class="show-sidebar">
                  <i class="fa fa-bars"></i>
                </a>
              </div>
              <div class="col-xs-4 col-sm-8 top-panel-right">
                <ul class="nav navbar-nav pull-right panel-menu">
                  <li class="dropdown">
                      <% if user_signed_in? %>
                    <a href="#" class="dropdown-toggle account" data-toggle="dropdown">
                      <i class="fa fa-angle-down pull-right"></i>
                      <div class="user-mini pull-right">
                        <span class="welcome">Welcome,</span>
                        <span><strong><%= current_user.email %></strong></span>
                      </div>
                    </a>
                    <ul class="dropdown-menu">
                        <li role="presentation">
                          <a href="<%= edit_user_registration_path  %>">
                            <i class="fa fa-user"></i>
                            <span class="hidden-sm text">Profile</span>
                          </a>
                        </li>
                        <li role="presentation">
                          <a href="<%= destroy_user_session_path%>" method="delete">
                            <i class="fa fa-power-off"></i>
                            <span class="hidden-sm text">Logout</span>
                          </a>
                          <%= link_to "Sign up", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        </li>
                      <% else %>
                        <li role="presentation">
                          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                        </li>
                        <li role="presentation">
                          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!--End Header-->

    <div id="main" class="container-fluid">
      <div class="row">
        <div id="sidebar-left" class="col-xs-2 col-sm-2">
          <ul class="nav main-menu">
            <li>
            <a href="<%= root_path %>"  class="active -link">
                <i class="fa fa-dashboard"></i>
                <span class="hidden-xs">Matrícula</span>
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle">
                <i class="fa fa-pencil-square-o"></i>
                <span class="hidden-xs">Cadastros</span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="" href="<%= students_path %>">Alunos</a></li>
                <li><a class="" href="<%= courses_path %>">Cursos</a></li>
              </ul>
            </li>
        </div>
        <!--Start Content-->
        <div id="content" class="col-xs-12 col-sm-10">
          <%= yield %>
          <div class="preloader">
          </div>
        </div>
      </div>

  </body>
</html>

app/views/layouts/login.html.erb
<html lang="en"><head>
<meta charset="utf-8">
<head>
  <title>SchoolAndClass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
    <script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <div class="container-fluid">
    <div id="page-login" class="row">
      <div class="col-xs-12 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>